language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - REPO=`pwd`
 - "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192"
 - "sudo apt-get -qq update"
install:
 - export PYTHONIOENCODING=UTF8 # just in case
 - cd $REPO
 - pip install -r requirements.txt --use-mirrors
script:
 - echo $REPO
 - cp conf/accounts.json.dist conf/accounts.json
 - cp conf/spamcan.json.dist conf/spamcan.json
 - python test.py