language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - REPO=`pwd`
 - echo $REPO
 - pwd
 - "sudo apt-get -qq update"
 - cp conf/accounts.json.dist conf/accounts.json
 - cp conf/spamcan.json.dist conf/spamcan.json
install:
 - export PYTHONIOENCODING=UTF8 # just in case
 - pwd
 - cd $REPO
 - pip install -r requirements.txt --use-mirrors